import { PortfolioData } from "@/types";

export const portfolioData: PortfolioData = {
  metadata: {
    title: "Ashutosh Jha | Full Stack Developer",
    description: "Ashutosh Jha - Full stack developer / Javascript is <3. Portfolio featuring MERN, Next.js, and modern web technologies.",
    keywords: "Ashutosh Jha, developer portfolio, github portfolio, Developer, AWS, CSS3, Docker, Express.js, JavaScript, Material UI, Next.js, Node.js, Nuxt.js, Python, TypeScript",
    author: "Ashutosh Jha",
    siteName: "Portfolio ",
    url: "https://github.com/Ashutoshjhaaa/Portfolio",
  },
  name: "Ashutosh Jha",
  role: "Full stack developer / Javascript is <3",
  bio: "Hey there! 👋 I'm Ashutosh, a **Full Stack Developer** specializing in **Next.js, Node.js,** and **PostgreSQL**. I build high-performance products like **Foodie-Frenzy** and **ShortIQ**, always focused on shipping fast, clean, and professional code.",
  profilePic: "https://github.com/Ashutoshjhaaa.png",
  email: "ashujha707070@gmail.com",
  cvUrl: "/Ashutoshjha reasume.pdf",
  socials: [
    { platform: "mail", url: "mailto:ashujha707070@gmail.com" },
    { platform: "github", url: "https://github.com/Ashutoshjhaaa" },
    { platform: "instagram", url: "https://ashutoshjha.me" },
    { platform: "linkedin", url: "https://www.linkedin.com/in/ashutoshjhadev" },
    { platform: "website", url: "https://ashutoshjha.me" },
    { platform: "x", url: "https://x.com/ashutoshjhadev" },
  ],
  skills: [
    { name: "HTML5", category: "Frontend" },
    { name: "CSS", category: "Frontend" },
    { name: "Tailwind CSS", category: "Frontend" },
    { name: "JavaScript", category: "Frontend" },
    { name: "TypeScript", category: "Frontend" },
    { name: "React", category: "Frontend" },
    { name: "Next.js", category: "Frontend" },
    { name: "Node.js", category: "Backend" },
    { name: "Express.js", category: "Backend" },
    { name: "Python", category: "Backend" },
    { name: "Java", category: "Backend" },
    { name: "Sass", category: "Frontend" },
    { name: "Vercel", category: "DevOps" },
    { name: "AWS", category: "Cloud" },
    { name: "PostgreSQL", category: "Database" },
    { name: "MongoDB", category: "Database" },
    { name: "Postman", category: "Tools" },
    { name: "MySQL", category: "Database" },
    { name: "Supabase", category: "Database" },
    { name: "Clerk", category: "Authentication" },
    { name: "Docker", category: "DevOps" },
    { name: "Material UI", category: "Frontend" },
    { name: "Radix UI", category: "UI" },
    { name: "Shadcn UI", category: "UI" },
    { name: "Convex", category: "Database" },
    { name: "Google Gemini", category: "AI" },
    { name: "git", category: "Tools" },
    { name: "github", category: "Tools" },
    { name: "VS Code", category: "Tools" },
    { name: "Google Gemini", category: "AI" },
    { name: "Neon", category: "Database" },
    { name: "Rozzerpay", category: "Tools" },
    { name: "Stripe", category: "Tools" },
    

  ],
  experience: [
    {
      company: "Digiglobe Solution PVT LTD",
      role: "Front End Developer Intern",
      duration: "Front End Developer Intern",
      logo: "",
    },
  ],
  projects: [
    {
      slug: "foodie-frenzy",
      name: "Foodie-Frenzy: Food Ordering Platform",
      description: "A high-performance full-stack food commerce engine featuring real-time order tracking, secure payments, and a centralized admin interface for inventory control and analytics.",
      status: "Live",
      techStack: ["React", "TypeScript", "Node.js", "Tailwind", "MongoDB", "Stripe"],
      logo: "/foodtrack/Foodi-Frenzy.png",
      color: "#fb7185",
      url: "https://foodie-frenzyy.vercel.app",
      githubUrl: "https://github.com/Ashutoshjhaaa/Foodie-Frenzy",
    },
    {
      slug: "shortiq",
      name: "ShortIQ: AI Faceless Content Engine",
      description: "An AI-powered automation platform that empowers creators to build and scale faceless content empires through seamless script generation, high-performance rendering, and direct social media publishing.",
      status: "Live",
      techStack: ["Next.js", "TypeScript", "PostgreSQL", "Tailwind"],
      logo: "/shortiq/logo.svg",
      color: "#fb7185",
      url: "https://short-iq-two.vercel.app",
      githubUrl: "https://github.com/Ashutoshjhaaa/ShortIQ",
    },

    {
      slug: "fit-track",
      name: "Fit-track- Your Personal Fitness Companion",
      description: "A personal fitness tracking app that helps users set goals, monitor progress, and stay motivated on their health journey.",
      status: "Live",
      techStack: ["React", "Node.js", "Tailwind", "Neon", "Clerk", "Radix UI"],
      logo: "/Fit-track/fit-track.svg",
      color: "green",
      url: "https://tryfittrack.vercel.app",
      githubUrl: "https://github.com/Ashutoshjhaaa/Fit-track",
    },
    {
      slug: "imagify",
      name: "Imagify- Create Images with AI",
      description: "A passionate developer crafting beautiful websites and stunning AI-generated images — where creativity meets code and imagination has no limits.",
      techStack: ["React", "Node.js", "Tailwind CSS", "Express.js", "MongoDB", "Rozzerpay", "Google Gemini"],
      status: "Live",
      logo: "/imagify/Imagify.svg",
      color: "grey",
      url: "https://imagify-img.vercel.app",
      githubUrl: "https://github.com/Ashutoshjhaaa/Imagify",
    },
  ],
  githubStats: {
    username: "ashutoshjhaaa",
    totalContributions: 83, // Real value from https://github-contributions-api.deno.dev/ashutoshjhaaa.json
  },
  apiUrls: {
    githubProfile: "https://github.com",
    githubRepo: "https://api.github.com/repos",
    githubContributions: "https://github-contributions-api.deno.dev/ashutoshjhaaa",
  },

  contact: {
    formspreeUrl: "https://formspree.io/f/mbdzbdko",
    title: "subhash.contact() — let's build something",
    nameLabel: "Name",
    namePlaceholder: "Your name",
    emailLabel: "Email",
    emailPlaceholder: "your@email.com",
    subjectLabel: "Subject",
    subjectPlaceholder: "What's this about?",
    messageLabel: "Message",
    messagePlaceholder: "Write your message here...",
    buttonIdle: "send_message.js",
    buttonSending: "sending...",
    successMessage: "✓ message sent!",
    replyWaitTime: "will reply soon",
  },
  titles: {
    skills: "Skills",
    experience: "Work Experience",
    projects: "Projects I've Made",
    github: "GitHub",
    githubSubtitle: "Highlights from my activity and pinned repositories.",
  },
  labels: {
    downloadCv: "Download CV",
    techStack: "Tech Stack",
    contributions: "contributions",
    pinned: "Pinned Repositories",
    share: "Share",
    copyright: "Ashutosh Jha",
    toggleTheme: "Toggle theme",
    lightMode: "Switch to light mode",
    darkMode: "Switch to dark mode",
    visitProfile: "Visit",
    cvAriaLabel: "Download curriculum vitae",
    socialsAriaLabel: "Social media links",
    projectIconAlt: "icon",
    shareSuccess: "Portfolio link copied to clipboard!",
  },
  githubCalendarConfig: {
    theme: {
      light: ['#ebedf0', '#9be9a8', '#40c463', '#30a14e', '#216e39'],
      dark: ['#161b22', '#0e4429', '#006d32', '#26a641', '#39d353'],
    },
    totalWeeks: 53,
    defaultBlockSize: 9,
    defaultBlockMargin: 2,
    paddingOffset: 48,
  },
  pinnedRepositories: []
};
